[project]
name = "learn-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.2",
    "django-tailwind>=4.0.1",
    "pillow>=11.2.1",
]
