# Generated by Django 5.2.2 on 2025-06-06 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_typs_imgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
