# Generated by Django 5.2.2 on 2025-06-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceAPP', '0002_auto_20250607_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_typs_imgs',
            name='type',
            field=models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('type3', 'Type 3'), ('type4', 'Type 4'), ('type5', 'Type 5')], default='image', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='all_typs_imgs',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
