# Generated by Django 5.2.2 on 2025-06-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceAPP', '0003_all_typs_imgs_type_alter_all_typs_imgs_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_typs_imgs',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
