# Generated by Django 5.2.2 on 2025-06-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceAPP', '0008_rename_isshu_date_imageprofile_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_typs_imgs',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='specific_image',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
