# Generated by Django 5.2.2 on 2025-06-10 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceAPP', '0009_alter_all_typs_imgs_name_alter_specific_image_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='specific_image',
            new_name='image_store',
        ),
        migrations.RenameField(
            model_name='image_store',
            old_name='image_types',
            new_name='image_type',
        ),
        migrations.RenameField(
            model_name='imageprofile',
            old_name='issue_date',
            new_name='isshu_date',
        ),
        migrations.AlterField(
            model_name='imageprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
